name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: MultiAPI.sln
      Test_Project_Path: MultiAPI_lib-framework\MultiAPI_Lib-framework.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Execute unit tests
      run: dotnet test

    - name: Restore the application
      run: dotnet restore $env:Solution_Name

    - name: Build the project
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Pack the project
      run: dotnet pack $env:Solution_Name -c Release -o output

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: output
